name: Fanaddixx
favicon: null
layout_spectrum: 0.9434
typography_spectrum: 0.07131
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f459d'
    - '#f2f2f3'
    - '#737cbc'
    - '#000000'
    - '#0000ff'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
