name: Fanaddixx
favicon: null
layout_spectrum: 0.032652226742357016
typography_spectrum: 0.6659991184715182
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.55496951402165
  lightness: 0.009204069850966334
  saturation: 0.2855261417571455
  rhythmicContrast: 0.3544922317378223
purpose: []
